name: Snyk
on:
    push:
        branches:
            - main
    workflow_dispatch:
permissions:
  contents: read
jobs:
    security:
        uses: guardian/.github/.github/workflows/sbt-node-snyk.yml@main
        with:
            ORG: guardian-dotcom-n2y
            SKIP_SBT: true
        secrets:
            SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
