# This action runs snyk monitor on every push to main
name: Snyk

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  security:
    uses: guardian/.github/.github/workflows/sbt-node-snyk.yml@2b60386db029f20e6f936b4b081881ea74af0077
    with:
      DEBUG: true
      ORG: guardian-dotcom-n2y
      SKIP_NODE: false
    secrets:
       SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
